remove dead links + add ession SII Grenoble 2023-11-30
TupperRust/tupperrust.github.io pull request #4
Opened 2023-11-18 17:42 UTC by JulioJu

2023-11-18 17:42 UTC, JulioJu commented on index.html
> -      </li>
@fflorent  IRC by Mozilla ne fonctionne plus je crois. C'est bien ça ?

2023-11-18 17:43 UTC, JulioJu commented on index.html
> -          <li> <a rel="nofollow" href="https://air.mozilla.org/5-ans-de-tuppervim-a-paris-2017-04-04/">Slides du 1er TupperRust [en]</a> par Ivan Enderlin (merci à lui pour cette superbe présentation
@fflorent le lien est mort

2023-11-18 17:45 UTC, JulioJu commented on index.html
>          <a rel="nofollow" href="https://framalistes.org/sympa/info/tupperrust">tupperrust@framalistes.org</a>
@fflorent  Est-ce qu'on supprime ou tu essaye de récupérer l'accès ?

2023-11-19 18:33 UTC, fflorent requested changes

2023-11-19 18:33 UTC, fflorent commented on index.html
> +      <strong><a href="https://sii-group.com/fr-FR/sii-rhone-alpes" rel="nofollow">SII</a> : <a href="https://www.google.com/maps/search/?api=1&query=45.183918%2C%205.703503">
Possible de plutôt mettre un lien OSM ?

https://www.openstreetmap.org/way/56016854#map=17/45.18393/5.70514

2023-11-19 18:33 UTC, fflorent commented on index.html
> -      </li>
Yep

2023-11-19 18:33 UTC, fflorent commented on index.html
> -          <li> <a rel="nofollow" href="https://air.mozilla.org/5-ans-de-tuppervim-a-paris-2017-04-04/">Slides du 1er TupperRust [en]</a> par Ivan Enderlin (merci à lui pour cette superbe présentation
OK, dommage

2023-11-19 18:33 UTC, fflorent commented on index.html
>          <a rel="nofollow" href="https://framalistes.org/sympa/info/tupperrust">tupperrust@framalistes.org</a>
En persévérant un peu plus, j'ai réussi à retrouver les accès :)

2023-11-19 19:11 UTC, merged

2023-11-19 19:11 UTC, JulioJu commented on index.html
> +      <strong><a href="https://sii-group.com/fr-FR/sii-rhone-alpes" rel="nofollow">SII</a> : <a href="https://www.google.com/maps/search/?api=1&query=45.183918%2C%205.703503">
Oui bien vu !